### ISSUE TITLE
Additional metrics tags like Common tags in Actuator

### ISSUE THREAD

**Issue by devgkz** [micronaut-projects/micronaut-micrometer#310]
### Feature description

Hello! 
I need ability to configure additional metrics tags like Common tags in Spring Boot Actuator.
Commons tags are applied to all meters and can be configured as shown in the following example:
```yaml
management:
  metrics:
    tags:
      region: "us-east-1"
      stack: "prod"
```
See Actuator docs https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.metrics.customizing.common-tags

This feature is planned for `micronaut-micrometer`?
